### ISSUE TITLE
Create react app  Unexpected token in ./node_modules/source-map-loader/dist/cjs.js

### ISSUE THREAD

**Issue by bigfree** [piotr-cz/redux-persist-idb-storage#14]
Hi,
I have application via create-react-app in redux template and when i use yours library it throws me this error:

```text
 Starting the development server...
redux_container  |
redux_container  | Failed to compile.
redux_container  |
redux_container  | Module parse failed: Unexpected token (13:16)
redux_container  | File was processed with these loaders:
redux_container  |  * ./node_modules/source-map-loader/dist/cjs.js
redux_container  | You may need an additional loader to handle the result of these loaders.
redux_container  | |
redux_container  | | export default function createIdbStorage(
redux_container  | >   definedOptions: {
redux_container  | |     name?: string
redux_container  | |     storeName?: string
redux_container  | ERROR in ./node_modules/@piotr-cz/redux-persist-idb-storage/src/index.ts 13:16
redux_container  | Module parse failed: Unexpected token (13:16)
redux_container  | File was processed with these loaders:
redux_container  |  * ./node_modules/source-map-loader/dist/cjs.js
redux_container  | You may need an additional loader to handle the result of these loaders.
redux_container  | |
redux_container  | | export default function createIdbStorage(
redux_container  | >   definedOptions: {
redux_container  | |     name?: string
redux_container  | |     storeName?: string
redux_container  |
redux_container  | webpack compiled with 1 error
redux_container  | Files successfully emitted, waiting for typecheck results...
redux_container  | Issues checking in progress...
redux_container  | No issues found.
```

when i use in .env:
```env
GENERATE_SOURCEMAP=false
```

error message is different:
```text
redux_container  | Starting the development server...
redux_container  |
redux_container  | Failed to compile.
redux_container  |
redux_container  | Module parse failed: Unexpected token (13:16)
redux_container  | You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
redux_container  | |
redux_container  | | export default function createIdbStorage(
redux_container  | >   definedOptions: {
redux_container  | |     name?: string
redux_container  | |     storeName?: string
redux_container  | ERROR in ./node_modules/@piotr-cz/redux-persist-idb-storage/src/index.ts 13:16
redux_container  | Module parse failed: Unexpected token (13:16)
redux_container  | You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
redux_container  | |
redux_container  | | export default function createIdbStorage(
redux_container  | >   definedOptions: {
redux_container  | |     name?: string
redux_container  | |     storeName?: string
redux_container  |
redux_container  | webpack compiled with 1 error
```

**i use react-scripts@5.0.1**

Could you please help me?
Thanks

**Comment by piotr-cz** [comment]
I was able to reproduce the issue when importing package with `/src` suffix.
Before I come up with a solution, try importing package like so:

```ts
import createIdbStorage from '@piotr-cz/redux-persist-idb-storage'
```

**Comment by bigfree** [comment]
I try, build is success but now there is an error in retrieving data from the DB 😢 
```text
redux-persist/getStoredState: Error restoring data [object Object] SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at defaultDeserialize (getStoredState.js:39:1)
    at getStoredState.js:23:1
```
The data is stored in the database, but when the page is refreshed, it is no longer in the database. However, the structure of the database remains the same.

**Store data:**
![image](https://user-images.githubusercontent.com/3304725/173056009-4dfffb27-6a00-4dcb-84b8-ece23869d78c.png)

**After refresh:**
![image](https://user-images.githubusercontent.com/3304725/173056150-de2f8206-bea2-456c-b50c-1c8b6c4b38d7.png)

My persist config:
```ts
const persistConfig: PersistConfig<any> = {
    key: 'root',
    version: 1,
    storage: createIdbStorage({
        name: 'craedit',
        storeName: 'craeditstore',
        version: 1
    }),
    timeout: 100,
    serialize: false,
    debug: true,
    blacklist: ['point']
};
```

**Comment by piotr-cz** [comment]
Yes, I can see that too with minimal reproduction

However It's another issue

**Comment by piotr-cz** [comment]
Which version of `redux-persist` are you using?

**Comment by bigfree** [comment]
> Which version of `redux-persist` are you using?

i use **redux-persist@6.0.0**

**Comment by piotr-cz** [comment]
Fixed in https://github.com/piotr-cz/redux-persist-idb-storage/commit/874425addad993b00409df553b95c459c65958ba

**Comment by piotr-cz** [comment]
Fixed in https://github.com/piotr-cz/redux-persist-idb-storage/commit/874425addad993b00409df553b95c459c65958ba
